version: 2
jobs:
  test:
    docker:
      - image: node:12.13.0-alpine
    steps:
      - checkout
      -run:
          name: "install package manager"
          commmand: "npm install"
      - run:
          name: "run test"
          command: "npm test"
workflows:
  version: 2
  runTest: 
    jobs:
      - test