version: 2
jobs:
  test:
    docker:
      - image: node:12.13.0-alpine
    steps:
      - checkout
      - run:
          name: "install package manager"
          command: "npm install"
      - run:
          name: "run test"
          command: "npx jest"
workflows:
  version: 2
  runTest:
    jobs:
      - test
